import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Upload,
  CheckCircle,
  AlertCircle,
  FileJson,
  Save,
} from "lucide-react";
import { questionBankService } from "@/services";
import {
  quizImportSchema,
  type QuizImportInput,
} from "@/utils/validators";
import { parseAIJson } from "@/utils/jsonCleanup";

interface ValidationError {
  path: string;
  message: string;
}

export function TeacherQuizImporterPage() {
  const [jsonInput, setJsonInput] = useState("");
  const [parsedData, setParsedData] = useState<QuizImportInput | null>(null);
  const [errors, setErrors] = useState<ValidationError[]>([]);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleValidate = () => {
    setErrors([]);
    setParsedData(null);
    setSaved(false);

    if (!jsonInput.trim()) {
      setErrors([{ path: "root", message: "Please paste JSON data first" }]);
      return;
    }

    let raw: unknown;
    try {
      raw = parseAIJson<unknown>(jsonInput);
    } catch (err) {
      setErrors([
        {
          path: "root",
          message:
            err instanceof Error ? err.message : "Invalid JSON format",
        },
      ]);
      return;
    }

    const result = quizImportSchema.safeParse(raw);

    if (!result.success) {
      const validationErrors: ValidationError[] = [];
      for (const issue of result.error.issues) {
        const path = issue.path.join(".");
        validationErrors.push({
          path: path || "root",
          message: issue.message,
        });
      }
      setErrors(validationErrors);
      return;
    }

    setParsedData(result.data);
    setErrors([]);
  };

  const handleImport = async () => {
    if (!parsedData) return;
    setSaving(true);

    try {
      const questions = parsedData.questions.map((q) => ({
        question: q.question,
        options: Object.entries(q.options).map(([id, text]) => ({
          id,
          text,
        })),
        correct_option: q.correctAnswer,
        subject: parsedData.subject,
        topic: parsedData.topic,
        difficulty: parsedData.difficulty.toLowerCase(),
        language: parsedData.language,
        marks: parsedData.marksPerQuestion,
        tags: [],
      }));

      await questionBankService.createQuestions(questions);
      setSaved(true);
    } catch (err) {
      setErrors([
        {
          path: "import",
          message:
            err instanceof Error ? err.message : "Failed to import questions",
        },
      ]);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Import Questions from JSON</h1>
        <p className="text-muted-foreground">
          Paste the JSON generated by ChatGPT or another AI tool, validate it,
          and import questions into the question bank.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Upload className="h-5 w-5" />
            Paste JSON Data
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="json-input">
              JSON from AI tool (ChatGPT, Claude, Gemini, etc.)
            </Label>
            <Textarea
              id="json-input"
              value={jsonInput}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => {
                setJsonInput(e.target.value);
                setErrors([]);
                setParsedData(null);
                setSaved(false);
              }}
              placeholder={`Paste your JSON here. Example:\n\n{\n  "title": "Hindi Grammar Quiz",\n  "subject": "Hindi",\n  "topic": "Grammar",\n  "classLevel": "Beginner",\n  "difficulty": "Medium",\n  "language": "Hindi",\n  "marksPerQuestion": 1,\n  "negativeMarks": 0,\n  "questionType": "MCQ",\n  "questions": [\n    {\n      "question": "Question text here",\n      "options": { "A": "...", "B": "...", "C": "...", "D": "..." },\n      "correctAnswer": "B"\n    }\n  ]\n}`}
              className="min-h-[300px] font-mono text-xs"
            />
          </div>

          {errors.length > 0 && (
            <div className="rounded-md border border-destructive/50 bg-destructive/10 p-4">
              <div className="flex items-center gap-2 mb-2">
                <AlertCircle className="h-4 w-4 text-destructive" />
                <p className="text-sm font-medium text-destructive">
                  Validation Errors ({errors.length})
                </p>
              </div>
              <ul className="space-y-1">
                {errors.map((err, idx) => (
                  <li key={idx} className="text-sm text-destructive">
                    {err.path !== "root" && (
                      <span className="font-mono mr-1">[{err.path}]</span>
                    )}
                    {err.message}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {parsedData && !saved && (
            <div className="rounded-md border border-green-500/50 bg-green-500/10 p-4">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className="h-4 w-4 text-green-600" />
                <p className="text-sm font-medium text-green-600">
                  JSON is valid! Ready to import.
                </p>
              </div>
              <div className="flex flex-wrap gap-2 mt-2">
                <Badge variant="outline">{parsedData.title}</Badge>
                <Badge variant="outline">{parsedData.subject}</Badge>
                <Badge variant="outline">{parsedData.topic}</Badge>
                <Badge variant="outline">
                  {parsedData.questions.length} questions
                </Badge>
                <Badge variant="outline">{parsedData.questionType}</Badge>
              </div>
            </div>
          )}

          {saved && (
            <div className="rounded-md border border-green-500/50 bg-green-500/10 p-4">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-600" />
                <p className="text-sm font-medium text-green-600">
                  Successfully imported {parsedData?.questions.length} questions
                  into the question bank!
                </p>
              </div>
            </div>
          )}

          <div className="flex gap-2 justify-end">
            <Button
              variant="outline"
              onClick={handleValidate}
              disabled={!jsonInput.trim()}
            >
              <FileJson className="h-4 w-4 mr-2" />
              Validate JSON
            </Button>
            <Button
              onClick={handleImport}
              disabled={!parsedData || saving || saved}
            >
              <Save className="h-4 w-4 mr-2" />
              {saving ? "Importing..." : "Import Questions"}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
