export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  COURSES: "/courses",
  COURSE_DETAIL: "/courses/:slug",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:slug",
  CONTACT: "/contact",
  ANNOUNCEMENTS: "/announcements",
  FAQ: "/faq",

  // Legacy generic auth (kept for backward compatibility)
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  // Student portal auth
  STUDENT_LOGIN: "/student/login",
  STUDENT_REGISTER: "/student/register",
  STUDENT_FORGOT_PASSWORD: "/student/forgot-password",

  // Teacher portal auth
  TEACHER_LOGIN: "/teacher/login",
  TEACHER_FORGOT_PASSWORD: "/teacher/forgot-password",

  // Admin portal auth
  ADMIN_LOGIN: "/admin/login",
  ADMIN_FORGOT_PASSWORD: "/admin/forgot-password",

  STUDENT_DASHBOARD: "/student/dashboard",
  STUDENT_COURSES: "/student/courses",
  STUDENT_COURSE_DETAIL: "/student/courses/:courseId",
  STUDENT_LESSONS: "/student/lessons",
  STUDENT_MATERIALS: "/student/materials",
  STUDENT_ASSIGNMENTS: "/student/assignments",
  STUDENT_QUIZZES: "/student/quizzes",
  STUDENT_RESULTS: "/student/results",
  STUDENT_ATTENDANCE: "/student/attendance",
  STUDENT_CERTIFICATES: "/student/certificates",
  STUDENT_AI_TUTOR: "/student/ai-tutor",
  STUDENT_NOTIFICATIONS: "/student/notifications",
  STUDENT_PROFILE: "/student/profile",

  TEACHER_DASHBOARD: "/teacher/dashboard",
  TEACHER_STUDENTS: "/teacher/students",
  TEACHER_COURSES: "/teacher/courses",
  TEACHER_LESSONS: "/teacher/lessons",
  TEACHER_ASSIGNMENTS: "/teacher/assignments",
  TEACHER_SUBMISSIONS: "/teacher/submissions",
  TEACHER_QUIZZES: "/teacher/quizzes",
  TEACHER_QUESTION_BANK: "/teacher/question-bank",
  TEACHER_QUIZ_IMPORTER: "/teacher/quiz-import",
  TEACHER_ATTENDANCE: "/teacher/attendance",
  TEACHER_PROGRESS: "/teacher/performance",
  TEACHER_ANNOUNCEMENTS: "/teacher/announcements",

  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_STUDENTS: "/admin/students",
  ADMIN_TEACHERS: "/admin/teachers",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_LESSONS: "/admin/lessons",
  ADMIN_MATERIALS: "/admin/materials",
  ADMIN_ASSIGNMENTS: "/admin/assignments",
  ADMIN_QUIZZES: "/admin/quizzes",
  ADMIN_QUESTION_BANK: "/admin/question-bank",
  ADMIN_AI_GENERATOR: "/admin/ai-generator",
  ADMIN_QUIZ_IMPORTER: "/admin/quiz-import",
  ADMIN_ATTENDANCE: "/admin/attendance",
  ADMIN_RESULTS: "/admin/results",
  ADMIN_CERTIFICATES: "/admin/certificates",
  ADMIN_BLOG: "/admin/blog",
  ADMIN_ANNOUNCEMENTS: "/admin/announcements",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_SETTINGS: "/admin/settings",
} as const;

export type RouteKey = keyof typeof ROUTES;
