export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  COURSES: "/courses",
  COURSE_DETAIL: "/courses/:slug",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:slug",
  CONTACT: "/contact",
  ANNOUNCEMENTS: "/announcements",
  FAQ: "/faq",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",

  // Separate portal auth
  STUDENT_LOGIN: "/student/login",
  STUDENT_REGISTER: "/student/register",
  STUDENT_FORGOT_PASSWORD: "/student/forgot-password",
  TEACHER_LOGIN: "/teacher/login",
  TEACHER_FORGOT_PASSWORD: "/teacher/forgot-password",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_FORGOT_PASSWORD: "/admin/forgot-password",

  STUDENT: {
    DASHBOARD: "/student/dashboard",
    COURSES: "/student/courses",
    COURSE_DETAIL: "/student/courses/:courseId",
    LESSONS: "/student/lessons",
    MATERIALS: "/student/materials",
    ASSIGNMENTS: "/student/assignments",
    QUIZZES: "/student/quizzes",
    QUIZ_ATTEMPT: "/student/quizzes/:quizId/attempt",
    RESULTS: "/student/results",
    ATTENDANCE: "/student/attendance",
    CERTIFICATES: "/student/certificates",
    AI_TUTOR: "/student/ai-tutor",
    SPEAKING: "/student/speaking",
    GRAMMAR: "/student/grammar",
    VOCABULARY: "/student/vocabulary",
    NOTIFICATIONS: "/student/notifications",
    PAYMENTS: "/student/payments",
    PROFILE: "/student/profile",
  },

  TEACHER: {
    DASHBOARD: "/teacher/dashboard",
    STUDENTS: "/teacher/students",
    COURSES: "/teacher/courses",
    LESSONS: "/teacher/lessons",
    MATERIALS: "/teacher/materials",
    ASSIGNMENTS: "/teacher/assignments",
    SUBMISSIONS: "/teacher/submissions",
    QUIZZES: "/teacher/quizzes",
    QUESTION_BANK: "/teacher/question-bank",
    QUIZ_IMPORTER: "/teacher/quiz-import",
    AI_GENERATOR: "/teacher/ai-generator",
    ATTENDANCE: "/teacher/attendance",
    PERFORMANCE: "/teacher/performance",
    ANNOUNCEMENTS: "/teacher/announcements",
    PROFILE: "/teacher/profile",
  },

  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    STUDENTS: "/admin/students",
    TEACHERS: "/admin/teachers",
    COURSES: "/admin/courses",
    LESSONS: "/admin/lessons",
    MATERIALS: "/admin/materials",
    ASSIGNMENTS: "/admin/assignments",
    QUIZZES: "/admin/quizzes",
    QUESTION_BANK: "/admin/question-bank",
    AI_GENERATOR: "/admin/ai-generator",
    QUIZ_IMPORTER: "/admin/quiz-import",
    ATTENDANCE: "/admin/attendance",
    RESULTS: "/admin/results",
    CERTIFICATES: "/admin/certificates",
    BLOG: "/admin/blog",
    ANNOUNCEMENTS: "/admin/announcements",
    NOTIFICATIONS: "/admin/notifications",
    PAYMENTS: "/admin/payments",
    REPORTS: "/admin/reports",
    ANALYTICS: "/admin/analytics",
    SETTINGS: "/admin/settings",
  },
} as const;
